import 'model_utils.dart';

// Represents a notification event generated by the system. --> maps to the 'notification_events' table in the database.
class NotificationEventModel {
  final String? id;
  final String patientId;
  final String? actorUserId;
  final String? recipientUserId;
  final String? recipientEmail;
  final String eventType;
  final String? entityType;
  final String? entityId;
  final String message;

  // The channel used for delivery
  final String deliveryChannel;
  final bool isSent;
  final DateTime? sentAt;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  const NotificationEventModel({
    this.id,
    required this.patientId,
    this.actorUserId,
    this.recipientUserId,
    this.recipientEmail,
    required this.eventType,
    this.entityType,
    this.entityId,
    required this.message,
    this.deliveryChannel = 'email',
    this.isSent = false,
    this.sentAt,
    this.createdAt,
    this.updatedAt,
  });

  factory NotificationEventModel.fromMap(Map map) {
    return NotificationEventModel(
      id: map['id']?.toString(),
      patientId: map['patient_id']?.toString() ?? '',
      actorUserId: map['actor_user_id']?.toString(),
      recipientUserId: map['recipient_user_id']?.toString(),
      recipientEmail: map['recipient_email']?.toString(),
      eventType: map['event_type']?.toString() ?? '',
      entityType: map['entity_type']?.toString(),
      entityId: map['entity_id']?.toString(),
      message: map['message']?.toString() ?? '',
      deliveryChannel: map['delivery_channel']?.toString() ?? 'email',
      isSent: asBool(map['is_sent']) ?? false,
      sentAt: asDateTime(map['sent_at']),
      createdAt: asDateTime(map['created_at']),
      updatedAt: asDateTime(map['updated_at']),
    );
  }

  Map<String, dynamic> toInsertMap() => cleanMap({
    // Notification rows are append-first. + elivery state can still be updated later by the service.
    'patient_id': patientId,
    'actor_user_id': actorUserId,
    'recipient_user_id': recipientUserId,
    'recipient_email': recipientEmail,
    'event_type': eventType,
    'entity_type': entityType,
    'entity_id': entityId,
    'message': message,
    'delivery_channel': deliveryChannel,
    'is_sent': isSent,
    'sent_at': sentAt?.toIso8601String(),
  });

  Map<String, dynamic> toUpdateMap() => cleanMap({
    'recipient_user_id': recipientUserId,
    'recipient_email': recipientEmail,
    'message': message,
    'delivery_channel': deliveryChannel,
    'is_sent': isSent,
    'sent_at': sentAt?.toIso8601String(),
  });

  Map<String, dynamic> toMap() => toInsertMap();
}
